stages:
  - build
  - test
  - report

before_script:
  - echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list
  - curl http://repo.ros2.org/repos.key | apt-key add -
  - apt-get update
  - apt-get install -y python3-colcon-common-extensions
  - source /opt/ros/crystal/setup.bash

build_launchtest:
  stage: build
  image: osrf/ros2:nightly
  script:
    - colcon build --packages-up-to apex_launchtest apex_launchtest_cmake
  artifacts:
    paths:
      - build
      - install 

build_all:
  stage: build
  image: osrf/ros2:nightly
  script:
    - colcon build --symlink-install
  artifacts:
    paths:
      - build
      - install

test_launchtest:
  stage: test
  image: osrf/ros2:nightly
  dependencies:
    - build_launchtest
  script:
    - pip3 install mock
    - colcon test --packages-select apex_launchtest apex_launchtest_cmake
    - colcon test-result --verbose
  artifacts:
    when: always
    paths:
      - log

test_all:
  stage: test
  image: osrf/ros2:nightly
  dependencies:
    - build_all
  script:
    - pip3 install mock
    - colcon test --pytest-args "--cov"
    - colcon test-result --verbose
  artifacts:
    when: always
    paths:
      - build
      - install
      - log
      - "*/.coverage"

coverage:
  stage: report
  image:
    name: python:3.6
  dependencies:
    - test_all
  before_script: []  # Don't need ROS setup for the coverage job
  script:
    - pip3 install coverage
    - find . -iname ".coverage" -exec coverage combine -a {} \;
    - coverage report --include=apex_launchtest*
    - coverage html --include=apex_launchtest*
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths:
      - htmlcov
